### ISSUE TITLE
Make license non-mandatory

### ISSUE THREAD

**Issue by gigaSproule** [gigaSproule/swagger-gradle-plugin#40]
As per the [spec](https://swagger.io/specification/#infoObject), license is not mandatory and so shouldn't be in the plugin.

**Comment by gigaSproule** [comment]
Fixed in the latest commit, will close this when released

**Comment by sharedprophet** [comment]
```
Execution failed for task ':generateSwaggerDocumentation'.
> info.licence.name is required by the swagger spec
```
The latest release still fails when there is no license if it gets info from `@SwaggerDefinition` annotation.

**Comment by gigaSproule** [comment]
So you have the required fields in the build.grade but it's using the annotation?

**Comment by sharedprophet** [comment]
No. I omit them from the build.gradle because I’d rather have all docs in annotations.

**Comment by gigaSproule** [comment]
Re-opened whilst I investigate it

**Comment by gigaSproule** [comment]
I have a test which shows it shouldn't care about license if it doesn't exist:
```
def 'Should not generate contact and license from annotations when info present but not contact or license'() {
    given:
    def apiSourceExtension = createApiSourceExtension()
    apiSourceExtension.info.contact = null
    apiSourceExtension.info.license = null

    when:
    annotationPopulator.populateExtensionsFromAnnotations(apiSourceExtension)

    then:
    apiSourceExtension.info.contact == null
    apiSourceExtension.info.license == null
}
```

I also removed the license from one of the samples, re-ran it and it produced a swagger file without license information. So not sure if it is something that has been fixed in what will be 1.0.5 or not.

With your setup, you are sure you're omitting _all_ license information right? As if you have the license object specified, but no name, then it's working correctly (as per [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#licenseObject)).

**Comment by gigaSproule** [comment]
Tried out a few more scenarios and it turns out that the annotation provides a default, so by default, it's invalid

**Comment by gigaSproule** [comment]
This should now be fixed...
